config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "dashboard#index"

  namespace :library do
    resources :borrows, only: [:index]
    resources :books do
      member do
        get :borrow_book
        get :return_book
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library.rb
module Library
  def self.table_name_prefix
    'library_'
  end
end

app/models/library/book.rb
# == Schema Information
#
# Table name: library_books
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  author_id  :integer
#  lead       :text(65535)
#  is_active  :boolean
#  aasm_state :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Library::Book < ApplicationRecord
  include AASM

  validates :name, :lead, :author, presence: true

  belongs_to :author, class_name: "User"
  has_many :borrows, class_name: '::Library::Borrow', dependent: :destroy

  default_scope { order(created_at: :desc) }

  aasm do
    state :available, :initial => true
    state :borrowed

    event :borrow do
      transitions :from => :available, :to => :borrowed
    end

    event :return do
      transitions :from => :borrowed, :to => :available
    end

  end

  def current_holder_id
    borrow = borrows.not_returned.first
    borrow.try(:user_id)
  end

  def to_s
    "#{name} (#{author})"
  end

end

app/models/library/borrow.rb
# == Schema Information
#
# Table name: library_borrows
#
#  id          :integer          not null, primary key
#  book_id     :integer
#  user_id     :integer
#  borrow_date :datetime
#  draw_date   :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Library::Borrow < ApplicationRecord



  belongs_to :user
  belongs_to :book, class_name: "::Library::Book"

  default_scope { order(created_at: :desc) }

  scope :not_returned, -> {where('draw_date IS NULL')}

  def can_be_returned?
    return self.draw_date.blank? ? true : false
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(255)
#

class User < ApplicationRecord

  validates :email, :name, presence: true

  devise :database_authenticatable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :books, class_name: '::Library::Book', foreign_key: 'author_id'
  has_many :borrows, class_name: '::Library::Borrow'

  def self.from_omniauth(access_token)
      data = access_token.info
      user = User.where(email: data['email']).first

      unless user
          user = User.create(name: data['name'],
             email: data['email'],
             password: Devise.friendly_token[0,20]
          )
      end
      user
  end

  def to_s
    name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :set_current_menu


  def set_current_menu
    @current_menu = controller_name
  end
  

  private

  def layout_by_resource
    if devise_controller?
      "application"
    else
      "library"
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    
  end
end

app/controllers/library/books_controller.rb
class Library::BooksController < ApplicationController
  before_action :set_library_book, only: [:show, :borrow_book, :return_book]
  before_action :set_user_library_book, only: [:edit, :update, :destroy]


  # GET /library/books
  # GET /library/books.json
  def index
    @library_books = Library::Book.all.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /library/books/1
  # GET /library/books/1.json
  def show
  end

  # GET /library/books/new
  def new
    @library_book = current_user.books.new
  end

  # GET /library/books/1/edit
  def edit
  end

  # POST /library/books
  # POST /library/books.json
  def create
    @library_book = current_user.books.new(library_book_params)

    respond_to do |format|
      if @library_book.save
        format.html { redirect_to @library_book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @library_book }
      else
        format.html { render :new }
        format.json { render json: @library_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /library/books/1
  # PATCH/PUT /library/books/1.json
  def update
    respond_to do |format|
      if @library_book.update(library_book_params)
        format.html { redirect_to @library_book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @library_book }
      else
        format.html { render :edit }
        format.json { render json: @library_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /library/books/1
  # DELETE /library/books/1.json
  def destroy
    @library_book.destroy
    respond_to do |format|
      format.html { redirect_to library_books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def borrow_book

    if @library_book.available?

      borrow = current_user.borrows.new(book_id: @library_book.id, borrow_date: DateTime.now())

      if borrow.save
        @library_book.borrow!
        redirect_to @library_book, notice: 'Książka została wypożyczona'
      else
        redirect_to library_books_url, alert: 'Wystąpił nieoczekiwany błąd.'
      end
    else
      redirect_to library_books_url, alert: 'Książka niedostępna.'
    end


  end

  def return_book

    if @library_book.borrowed?

      borrow = current_user.borrows.find_by_book_id(@library_book.id)

      if borrow.update({:draw_date => DateTime.now()})
        @library_book.return!
        redirect_to @library_book, notice: 'Książka została zwrócona'
      else
        redirect_to library_books_url, alert: 'Wystąpił nieoczekiwany błąd.'
      end
    else
      redirect_to library_books_url, alert: 'Książka jest dostępna do wypożyczenia.'
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library_book
      @library_book = Library::Book.find(params[:id])
    end

    def set_user_library_book
      @library_book = current_user.books.find_by_id(params[:id])
      return head 404 if @library_book.blank?
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def library_book_params
      params.require(:library_book).permit(:name, :lead, :is_active)
    end
end

app/controllers/library/borrows_controller.rb
class Library::BorrowsController < ApplicationController

  # GET /library/borrows
  # GET /library/borrows.json
  def index
    @library_borrows = Library::Borrow.all.paginate(:page => params[:page], :per_page => 10)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def datetime(date)
    date.strftime('%d/%m/%Y %H:%M') unless date.blank?
  end

end

app/helpers/library/books_helper.rb
module Library::BooksHelper
end

app/helpers/library/borrows_helper.rb
module Library::BorrowsHelper
end

app/views/dashboard/index.html.erb
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Dashboard</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <a href="<%= new_library_book_path %>" class="btn btn-sm btn-outline-secondary">Dodaj ksiązkę do biblioteki!</a>
      </div>
    </div>
  </div>


  <h3>Twoje dodane książki</h3>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Tytuł</th>
          <th>Aktywna?</th>
          <th>Data dodania</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% current_user.books.each do |book| %>
        <tr>
          <td><%= link_to book.name, book %></td>
          <td><%= book.is_active? ? 'tak' : 'nie' %></td>
          <td><%= datetime(book.created_at) %></td>
          <td>
            <%= link_to 'Edytuj', edit_library_book_path(book), :class => 'fa fa-pencil', title: 'Edytuj' %>
            <%= link_to 'Usuń', book, method: :delete, data: { confirm: 'Czy jesteś pewien?' } %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>


  <h3>Twoja historia wypożyczeń</h3>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Książka</th>
          <th>Wypożyczona</th>
          <th>Oddana</th>
        </tr>
      </thead>
      <tbody>
      <% current_user.borrows.each do |borrow| %>
        <tr>
          <td><%= borrow.book %></td>
          <td><%= datetime(borrow.borrow_date) %></td>
          <td><%= borrow.draw_date.blank? ? link_to('Zwróć', return_book_library_book_path(borrow.book), class: 'btn btn-sm btn-success') : datetime(borrow.draw_date) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestLibrary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if notice %>

      <div class="alert-absolute alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

    <% end %>

    <% if alert %>

      <div class="alert-absolute alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

    <% end %>

      <%= yield %>

  </body>
</html>

app/views/layouts/library.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestLibrary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'library', media: 'all' %>
    <%= javascript_include_tag 'library' %>
  </head>

  <body>

    <%= render partial: '/shared/navbar_top' %>


<div class="container-fluid">
      <div class="row">

      <%= render partial: '/shared/sidebar' %>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        

        <% if notice %>

          <div class="alert-absolute alert alert-success alert-dismissible fade show" role="alert">
            <%= notice %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

        <% end %>

        <% if alert %>

          <div class="alert-absolute alert alert-danger alert-dismissible fade show" role="alert">
            <%= alert %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

        <% end %>


        <%= yield %>


        </main>

      </div>
    </div>


  </body>
</html>

app/views/library/books/_form.html.erb
<div class="row">
  <div class="col-lg-6 col-xs-12">
  
    <%= form_for(library_book) do |f| %>
      <% if library_book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(library_book.errors.count, "error") %> prohibited this library_book from being saved:</h2>

          <ul>
          <% library_book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :lead %>
        <%= f.text_area :lead, :class => 'form-control' %>
      </div>

      <div class="form-check">
        <%= f.check_box :is_active, :class => 'form-check-input' %>
        <%= f.label :is_active %>
      </div>

      <div class="actions">
        <%= f.submit "Zapisz", class: 'btn btn-primary' %>
      </div>
    <% end %>

  </div>
</div>

app/views/library/books/edit.html.erb
<h1>Edytuj książkę</h1>

<%= render 'form', library_book: @library_book %>

app/views/library/books/index.html.erb
<div class="row">
    <div class="col-lg-8 col-xs-12"><h1>Książki</h1></div>
    <div class="col-lg-4 col-xs-12 text-right">
      <%= link_to 'Dodaj książkę', new_library_book_path, :class => 'btn btn-sm btn-outline-secondary' %>
    </div>
</div>



<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>Nazwa</th>
        <th>Autor</th>
        <th>Dostępna?</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @library_books.each do |library_book| %>
      <tr>
        <td><%= link_to library_book.name, library_book %></td>
        <td><%= library_book.author %></td>
        <td><%= library_book.is_active? ? 'tak' : 'nie' %></td>
        <td>
          <%= library_book.aasm_state %>
          <% if library_book.available? && library_book.is_active? %>  
            <%= link_to 'Wypożycz', borrow_book_library_book_path(library_book) %>
          <% end %>
        </td>
        <td>
          <% if current_user == library_book.author %>
            <%= link_to 'Edytuj', edit_library_book_path(library_book), :class => 'fa fa-pencil', title: 'Edytuj' %>
            <%= link_to 'Usuń', library_book, method: :delete, data: { confirm: 'Czy jesteś pewien?' } %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="5" class="text-center"><%= will_paginate @library_books %></td>
      </tr>
    </tfoot>
  </table>
</div>

app/views/library/books/new.html.erb
<h1>Dodaj nową książkę</h1>

<%= render 'form', library_book: @library_book %>

app/views/library/books/show.html.erb
<div class="card">
  <div class="card-header">
    <h5 class="float-left"><%= @library_book.name %></h5>
    <% if current_user == @library_book.author %>
      <%= link_to 'Edytuj', edit_library_book_path(@library_book), class: 'btn btn-primary float-right' %>
    <% end %>
    <div class="clearfix"></div>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <em><%= simple_format(@library_book.lead) %></em>
      <footer class="blockquote-footer">Autor: <cite title="<%= @library_book.author %>"><%= @library_book.author %></cite></footer>
    </blockquote><br/>

    <% if @library_book.available? && @library_book.is_active? %>

      <%= link_to 'Wypożycz', borrow_book_library_book_path(@library_book), class: 'btn btn-primary' %>

    <% elsif @library_book.current_holder_id == current_user.id %>

      <%= link_to 'Zwróć', return_book_library_book_path(@library_book), class: 'btn btn-success' %>

    <% end %>

  </div>
</div>

app/views/library/borrows/index.html.erb
<h1>Historia wypożyczeń</h1>

<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>Książka</th>
        <th>Czytelnik</th>
        <th>Data wypożyczenia</th>
        <th>Data zwrotu</th>
      </tr>
    </thead>
    <tbody>
      <% @library_borrows.each do |library_borrow| %>
      <tr>
        <td><%= library_borrow.book %></td>
        <td><%= library_borrow.user %></td>
        <td><%= datetime(library_borrow.borrow_date) %></td>
        <td><%= datetime(library_borrow.draw_date) %></td>
      </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="4" class="text-center"><%= will_paginate @library_borrows %></td>
      </tr>
    </tfoot>
  </table>
</div>

app/views/shared/_navbar_top.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <div class="navbar-user">Witaj <%= current_user %> !</div>
    
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <%= link_to 'Wyloguj', destroy_user_session_path, :method => :delete, class: 'btn btn-sm btn-outline-secondary' %>
      </li>
    </ul>
  </nav>
<% end %>

  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

app/views/shared/_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to "Dashboard", root_path, :class => "nav-link #{'active' if @current_menu == 'dashboard'}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Książki", library_books_path, :class => "nav-link #{'active' if @current_menu == 'books'}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Historia wypożyczeń", library_borrows_path, :class => "nav-link #{'active' if @current_menu == 'borrows'}" %>
      </li>
    </ul>
  </div>
</nav>